/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/NkHMuOylnTL
 */
import Link from "next/link"
import { Card } from "@/components/ui/card"

export default function page() {
  return (
    <div key="1" className="flex flex-col min-h-screen bg-blue-100 dark:bg-black">
      <header className="py-10 px-6 bg-blue-500 dark:bg-gray-900">
        <Link className="text-white" href="/">
          <ArrowLeftIcon className="h-6 w-6" />
          <span className="sr-only">Back</span>
        </Link>
        <h1 className="text-4xl font-bold text-white">CNC Machine</h1>
      </header>
      <main className="flex-1">
        <section className="py-10 px-6">
          
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 mt-6">
            <Card className="bg-white dark:bg-gray-800">
              <img
                alt="Project Image 1"
                className="w-full h-100 object-cover"
                height="200"
                src="/images/20240123_133029.jpg"
                style={{
                  aspectRatio: "200/200",
                  objectFit: "cover",
                }}
                width="200"
              />
            </Card>
            <Card className="bg-white dark:bg-gray-800">
              <img
                alt="Project Image 2"
                className="w-full h-100 object-cover"
                height="200"
                src="/images/20240123_133043.jpg"
                style={{
                  aspectRatio: "200/200",
                  objectFit: "cover",
                }}
                width="200"
              />
            </Card>
            <Card className="bg-white dark:bg-gray-800">
              <img
                alt="Project Image 3"
                className="w-full h-100 object-cover"
                height="200"
                src="/images/CNC in action.PNG"
                style={{
                  aspectRatio: "200/200",
                  objectFit: "cover",
                }}
                width="200"
              />
            </Card>
          </div>
                

 <div className="grid grid-cols-1 gap-6 mt-4 w-9/10 mx-auto">
              <img
                
                className="w-full h-full object-cover"
                
                src="/images/20240123_133016.jpg"
                style={{
                 
                  objectFit: "cover",
                }}
                />
                </div>
          <div className="mt-10">
         

            <h3 className="text-xl font-bold text-blue-900 dark:text-gray-200 mt-10">About the Project</h3>
            
            <h4 className=" font-bold text-l mt-4 text-gray-600 dark:text-gray-400">
            Overview:
            </h4>
            <p className="ml-10 mt-4 text-gray-600 dark:text-gray-400">
              This project features a custom-built CNC (Computer Numerical Control) machine, epitomizing advanced mechanical engineering and control systems. It combines durable materials with sophisticated technology, offering high precision and versatility in machining.
            </p>
            <h4 className=" font-bold text-l mt-4 text-gray-600 dark:text-gray-400">
                Frame Construction:
              </h4>
                  <div>
                    <p className=" mt-4 ml-10 text-gray-600 dark:text-gray-400">
                          The frame of the machine is constructed from welded steel, ensuring a sturdy and durable base. This design focuses on stability and rigidity to maintain precision during machining processes.
                    </p></div>
              <h4 className=" font-bold text-l mt-4 text-gray-600 dark:text-gray-400">
                    Axis Movement:
              </h4>

                    <p className=" ml-10 mt-4 text-gray-600 dark:text-gray-400">
                          The machine employs guided chromed rods and carriages for axis movement, providing smooth, accurate, and consistent motion.
                    </p>
             
             
              <h4 className=" font-bold text-l mt-4 text-gray-600 dark:text-gray-400">
              Drive System:
              </h4>
              <p className="ml-10 mt-4 text-gray-600 dark:text-gray-400">
              Ball screws are used in the drive system, chosen for their superior accuracy and efficiency. This selection offers gear reduction advantages, enhancing torque while maintaining precision.
              </p>
              <h4 className=" font-bold text-l mt-4 text-gray-600 dark:text-gray-400">
              Spindle:
              </h4>
              <p className="ml-10 mt-4 text-gray-600 dark:text-gray-400">

              The spindle is a powerful 2.2KW water-cooled model, capable of reaching speeds up to 22,000 RPM. Speed control is managed by a Variable Frequency Drive (VFD), allowing precise adjustments.
              </p>
              <h4 className=" font-bold text-l mt-4 text-gray-600 dark:text-gray-400">
              Control System:
              </h4>
              <p className="ml-10 mt-4 text-gray-600 dark:text-gray-400">
              At its core, the machine is controlled by an Arduino Nano running GRBL, with commands fed through Universal Gcode Sender. This setup facilitates easy programming and operation of the machine.
              </p>
              <h4 className=" font-bold text-l mt-4 text-gray-600 dark:text-gray-400">
              Build Volume:
              </h4>
              <p className="ml-10 mt-4 text-gray-600 dark:text-gray-400">
              The machine boasts a substantial build volume of 1.5m x 1.5m x 200mm, accommodating large-scale projects and a variety of material sizes.
              </p>
              <h4 className=" font-bold text-l mt-4 text-gray-600 dark:text-gray-400">
              Stepper Motors:
              </h4>
              <p className=" ml-10 mt-4 text-gray-600 dark:text-gray-400">
              It utilizes high precision NEMA 23 motors for the stepper systems, ensuring accurate and consistent movement across all CNC axes.
              </p>
              <h4 className=" font-bold text-l mt-4 text-gray-600 dark:text-gray-400">
              Machine Resolution:
              </h4>
              <p className="ml-10 mt-4 text-gray-600 dark:text-gray-400">
              The machine offers a high resolution of 0.016mm, capable of cutting wood, plastics, and aluminium with exceptional precision.
                </p>
                <h4 className=" font-bold text-l mt-4 text-gray-600 dark:text-gray-400">
              Versatility:
              </h4>
              <p className="ml-10 mt-4 text-gray-600 dark:text-gray-400">
              Adding to its functionality, the machine can be equipped with a laser cutter attachment, expanding its capabilities to include both traditional CNC machining and laser cutting operations.

              In summary, this custom-built CNC machine is a fusion of robust design and advanced technology, making it suitable for precision machining in diverse materials and applications. The inclusion of a laser cutter attachment further enhances its utility, marking it as a valuable asset in various workshop and manufacturing settings.
                          </p>
          </div>
        </section>
      </main>
      <footer className="py-10 px-6 bg-blue-500 dark:bg-gray-900">
        <h2 className="text-2xl font-bold text-white">Contact</h2>
        <p className="mt-2 text-white">Email: mgshepstone@gmail.com</p>
        <p className="mt-2 text-white">Phone: (+27) 66 258 8727</p>
        
      </footer>
    </div>
  )
}


function ArrowLeftIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m12 19-7-7 7-7" />
      <path d="M19 12H5" />
    </svg>
  )
}


function TwitterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}


function GithubIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0-1-3.5c3 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2c-.3 1.15-.3 2.35 3.5A5.403 5.403 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  )
}


function LinkedinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 1 6v7h-4v-7a2 2 0-2-2 0-2 2v7h-4v-7a6 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}
